### ISSUE TITLE
Nivel de Amistad

### ISSUE THREAD

**Issue by soynoov** [soynoov/voidegon#14]
Adaptar el nivel de amistad en formato vertical, esto hará que sea más responsive y puedas adaptarlo a un mejor diseño.

**Comment by Kirhia** [comment]
![WhatsApp Image 2024-04-22 at 00 50 37](https://github.com/soynoov/voidegon/assets/140663950/8118121c-5df9-45e6-b506-e2f4934b6bc8)

**Comment by Kirhia** [comment]
con lo de hacer un menu exclusivo de amistades me refiero a hacer una tabla tipo stardew valley
